"""Initial migration

Revision ID: caa659a569b5
Revises: 
Create Date: 2024-06-02 02:35:57.669421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caa659a569b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balances',
    sa.Column('asset', sa.String(), nullable=False),
    sa.Column('balance', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('asset')
    )
    op.create_table('ledgers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('refid', sa.String(), nullable=False),
    sa.Column('time', sa.Float(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('subtype', sa.String(), nullable=True),
    sa.Column('aclass', sa.String(), nullable=False),
    sa.Column('asset', sa.String(), nullable=False),
    sa.Column('amount', sa.String(), nullable=False),
    sa.Column('fee', sa.String(), nullable=False),
    sa.Column('balance', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledgers_id'), 'ledgers', ['id'], unique=False)
    op.create_table('nonces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_history',
    sa.Column('trade_id', sa.String(), nullable=False),
    sa.Column('ordertxid', sa.String(), nullable=False),
    sa.Column('postxid', sa.String(), nullable=False),
    sa.Column('pair', sa.String(), nullable=False),
    sa.Column('time', sa.Float(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('ordertype', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('cost', sa.String(), nullable=False),
    sa.Column('fee', sa.String(), nullable=False),
    sa.Column('vol', sa.String(), nullable=False),
    sa.Column('margin', sa.String(), nullable=False),
    sa.Column('misc', sa.String(), nullable=True),
    sa.Column('maker', sa.Boolean(), nullable=False),
    sa.Column('posstatus', sa.String(), nullable=True),
    sa.Column('cprice', sa.Float(), nullable=True),
    sa.Column('ccost', sa.Float(), nullable=True),
    sa.Column('cfee', sa.Float(), nullable=True),
    sa.Column('cvol', sa.Float(), nullable=True),
    sa.Column('cmargin', sa.Float(), nullable=True),
    sa.Column('net', sa.Float(), nullable=True),
    sa.Column('trades', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('trade_id')
    )
    op.create_index(op.f('ix_trade_history_trade_id'), 'trade_history', ['trade_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_history_trade_id'), table_name='trade_history')
    op.drop_table('trade_history')
    op.drop_table('nonces')
    op.drop_index(op.f('ix_ledgers_id'), table_name='ledgers')
    op.drop_table('ledgers')
    op.drop_table('balances')
    # ### end Alembic commands ###
